### ISSUE TITLE
Europe/Africa/Middle East regions are not being parsed since 4/28/2020

### ISSUE THREAD

**Issue by aaronalberg** [burib/aws-region-table-parser#16]
The eu/me/af regions are no longer being updated when the parser runs for some reason

**Comment by burib** [comment]
Thanks @aaronalberg

Probably the underlying html got changed. I'll have time to fix it around the weekend of July 14.

**Comment by burib** [comment]
@aaronalberg I've fixed the issue. All Regions are available now here: https://github.com/burib/aws-region-table-parser/tree/master/data

**Comment by burib** [comment]
@aaronalberg or almost fixed it. us-east-1 gone missing. let me check.

**Comment by burib** [comment]
@aaronalberg alright. it's back.

**Comment by aaronalberg** [comment]
Thanks so much!
