### ISSUE TITLE
Typo in Melbourne Region's id (ap-southeast-4 instead of ap-northeast-4)

### ISSUE THREAD

**Issue by Gokulnath-Venugopal** [burib/aws-region-table-parser#26]
In the generate-json.js file, the melbourne region should be ap-southeast-4 instead of ap-northeast-4

**Comment by burib** [comment]
thank you @Gokulnath-Venugopal for reporting the issue. It's fixed now.

https://github.com/burib/aws-region-table-parser/blob/master/region_code_to_name_map.json#L12
https://github.com/burib/aws-region-table-parser/blob/master/data/region_info/ap-southeast-4.json
